local opts = { noremap = true, silent = true }

-- tmux-sessionizer (https://github.com/datsfilipe/unix-scripts/blob/main/tmux-sessionizer)
-- vim.keymap.set('n', '<C-f>', ':silent !tmux neww tmux-sessionizer<Return>', opts)

-- zellij-sessionizer (https://github.com/datsfilipe/unix-scripts/blob/main/zellij-sessionizer)
vim.keymap.set('n', '<C-f>', function()
  io.popen('zellij-sessionizer'):close()
end, opts)

-- zellij-session-nav (https://github.com/datsfilipe/unix-scripts/blob/main/zellij-session-nav)
vim.keymap.set('n', '<A-0>', function()
  io.popen('zellij-session-nav --headless 0'):close()
end, opts)
vim.keymap.set('n', '<A-1>', function()
  io.popen('zellij-session-nav --headless 1'):close()
end, opts)
vim.keymap.set('n', '<A-2>', function()
  io.popen('zellij-session-nav --headless 2'):close()
end, opts)
vim.keymap.set('n', '<A-3>', function()
  io.popen('zellij-session-nav --headless 3'):close()
end, opts)
vim.keymap.set('n', '<A-4>', function()
  io.popen('zellij-session-nav --headless 4'):close()
end, opts)
vim.keymap.set('n', '<A-5>', function()
  io.popen('zellij-session-nav --headless 5'):close()
end, opts)
vim.keymap.set('n', '<A-6>', function()
  io.popen('zellij-session-nav --headless 6'):close()
end, opts)
vim.keymap.set('n', '<A-7>', function()
  io.popen('zellij-session-nav --headless 7'):close()
end, opts)
vim.keymap.set('n', '<A-8>', function()
  io.popen('zellij-session-nav --headless 8'):close()
end, opts)
vim.keymap.set('n', '<A-9>', function()
  io.popen('zellij-session-nav --headless 9'):close()
end, opts)
