return {
  'folke/trouble.nvim',
  keys = {
    { ';e', '<cmd>Trouble diagnostics toggle<Return>' },
    { ';b', '<cmd>Trouble diagnostics toggle filter.buf=0<Return>' },
    { ']d', '<cmd>Trouble diagnostics next<Return>' },
    { '[d', '<cmd>Trouble diagnostics prev<Return>' },
  },
  opts = {
    focus = true,
    follow = true,
    use_diagnostic_signs = true,
    icons = {
      indent = {
        fold_open = ' ',
        fold_closed = ' ',
        ws = '',
      },
      folder_closed = '',
      folder_open = '',
      kinds = {
        Array = '',
        Boolean = '',
        Class = '',
        Constant = '',
        Constructor = '',
        Enum = '',
        EnumMember = '',
        Event = '',
        Field = '',
        File = '',
        Function = '',
        Interface = '',
        Key = '',
        Method = '',
        Module = '',
        Namespace = '',
        Null = '',
        Number = '',
        Object = '',
        Operator = '',
        Package = '',
        Property = '',
        String = '',
        Struct = '',
        TypeParameter = '',
        Variable = '',
      },
    },
  },
}
