require 'user.plugins.colorschemes'
require 'user.plugins.console'
require 'user.plugins.fidget'
require 'user.plugins.fzf-lua'
require 'user.plugins.indentmini'
require 'user.plugins.lspconfig'
require 'user.plugins.minidiff'
require 'user.plugins.oil'
